# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'Menu.ui'
#
# Created by: PyQt5 UI code generator 5.15.0
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.

import sys
from PyQt5 import QtWidgets,QtCore,QtGui
from PyQt5.QtCore import *
from PyQt5.QtGui import *
from PyQt5.QtWidgets import *
import IMS.LoginIn1
from IMS.Delete import Delete as delete
import IMS.View
import IMS.Add
from IMS.Update import Update as update



class Ui_Form(QWidget):
    def __init__(self,file):
        super(Ui_Form,self).__init__()
        self.setupUi(self,file)



    def setupUi(self, Form,file):
        self.file = file
        Form.setObjectName("Form")
        Form.resize(1205, 686)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(Form.sizePolicy().hasHeightForWidth())
        Form.setSizePolicy(sizePolicy)

        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(Form)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setContentsMargins(0, 0, -1, -1)
        self.horizontalLayout_2.setSpacing(6)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")

        self.listWidget = QtWidgets.QListWidget(Form)
        self.listWidget.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(2)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.listWidget.sizePolicy().hasHeightForWidth())
        self.listWidget.setSizePolicy(sizePolicy)
        self.listWidget.setMaximumSize(QtCore.QSize(197, 16777215))

        self.listWidget.setStyleSheet("QListWidget{background-color:#FFFFF0;color:rgb(200,200,200);border:2px solid PaleGreen;border-radius: 4px;}" # listwidget背景样式
                                      "QListWidget:Item{padding-top:15px; padding-bottom:15px;}" # 字体上下空白大小
                                      "QListWidget::Item:hover{background:PaleGreen; }" # 鼠标移动至Item时
                                      "QListWidget::item:selected{background:LightGreen; color:DimGrey;}" # 选中时
                                      )
        # set listWidget item style
        View = QListWidgetItem(QIcon("D:\Project\IMS\\frequency.ico"),'View')
        #View.setTextAlignment(Qt.AlignHCenter|Qt.AlignVCenter)
        Add = QListWidgetItem(QIcon("D:\Project\IMS\\frequency.ico"), 'Add')
        Delete = QListWidgetItem(QIcon("D:\Project\IMS\\frequency.ico"), 'Delete')
        Update = QListWidgetItem(QIcon("D:\Project\IMS\\frequency.ico"), 'Update')
        self.listWidget.insertItem(0, View)
        self.listWidget.insertItem(1, Add)
        self.listWidget.insertItem(2, Delete)
        self.listWidget.insertItem(3, Update)
        self.listWidget.currentRowChanged.connect(self.display)

        self.listWidget.setObjectName("listWidget")
        self.horizontalLayout_2.addWidget(self.listWidget)

        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(10)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.stackedWidget.sizePolicy().hasHeightForWidth())
        self.stackedWidget.setSizePolicy(sizePolicy)
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.page_3.setLayout(IMS.View.view().setupUi(self.file))
        self.page_4 = QtWidgets.QWidget()
        self.page_4.setObjectName("page_4")
        self.stackedWidget.addWidget(self.page_4)
        self.page_5 = QtWidgets.QWidget()
        self.page_4.setLayout(IMS.Add.Ui_Form().setupUi(self.file))

        self.page_5.setObjectName("page_5")
        self.stackedWidget.addWidget(self.page_5)
        self.page_6 = QtWidgets.QWidget()
        self.page_5.setLayout(delete())

        self.page_6.setObjectName("page_6")
        self.stackedWidget.addWidget(self.page_6)
        self.page_6.setLayout(update())

        self.horizontalLayout_2.addWidget(self.stackedWidget)
        self.horizontalLayout_3.addLayout(self.horizontalLayout_2)


##################################################################################
        # ##查找页面
        # self.gridLayout = QtWidgets.QGridLayout()
        # self.gridLayout.setContentsMargins(0, 0, 0, 0)
        # self.gridLayout.setObjectName("gridLayout")
        # # 输入栏
        # self.lineEdit = QtWidgets.QLineEdit()
        # self.lineEdit.setEnabled(False)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(5)
        # sizePolicy.setVerticalStretch(1)
        # sizePolicy.setHeightForWidth(self.lineEdit.sizePolicy().hasHeightForWidth())
        # self.lineEdit.setSizePolicy(sizePolicy)
        # self.lineEdit.setObjectName("lineEdit")
        # self.gridLayout.addWidget(self.lineEdit, 4, 1, 1, 2)
        # # 查询按钮
        # self.pushButton = QtWidgets.QPushButton()
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(3)
        # sizePolicy.setVerticalStretch(1)
        # sizePolicy.setHeightForWidth(self.pushButton.sizePolicy().hasHeightForWidth())
        # self.pushButton.setSizePolicy(sizePolicy)
        # self.pushButton.setObjectName("pushButton")
        # self.pushButton.setText("查找")
        # self.gridLayout.addWidget(self.pushButton, 4, 4, 1, 1)
        # self.pushButton.clicked.connect(lambda: self.upd())  # view().type(self.comboBox.currentIndex(), self.lineEdit, self.file,self.model)
        # # 选择查询方式
        # self.comboBox = QtWidgets.QComboBox()
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(3)
        # sizePolicy.setVerticalStretch(2)
        # sizePolicy.setHeightForWidth(self.comboBox.sizePolicy().hasHeightForWidth())
        # self.comboBox.setSizePolicy(sizePolicy)
        # self.comboBox.setObjectName("comboBox")
        # # self.comboBox.addItem("查找全部")
        # # self.comboBox.addItem("按学号查找")
        # # self.comboBox.addItem("按姓名查找")
        # # self.comboBox.addItem("按专业查找")
        # # self.comboBox.addItem("按课程名查找")
        # self.comboBox.addItems(["查找全部", "按学号查找", "按姓名查找", "按专业查找", "按课程名查找"])
        # self.comboBox.currentIndexChanged.connect(lambda: self.sel())
        # self.gridLayout.addWidget(self.comboBox, 4, 3, 1, 1)
        # # 显示模块
        # self.tableView = QtWidgets.QTableView()
        # ssizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(50)
        # sizePolicy.setHeightForWidth(self.tableView.sizePolicy().hasHeightForWidth())
        # self.tableView.setSizePolicy(sizePolicy)
        # self.tableView.setObjectName("tableView")
        # self.gridLayout.addWidget(self.tableView, 5, 1, 1, 4)
        #
        # self.model = QStandardItemModel()
        # self.model.setHorizontalHeaderLabels(['Sno', 'Name', 'Age', "Sex", "Is", "Course"])
        # self.tableView.setModel(self.model)
        # # 水平方向标签拓展剩下的窗口部分，填满表格
        # self.tableView.horizontalHeader().setStretchLastSection(True)
        # # 水平方向，表格大小拓展到适当的尺寸
        # self.tableView.horizontalHeader().setSectionResizeMode(QHeaderView.Stretch)
        # # tableView.setEnabled(False)  #设置表格不可编
        #
        # # 标题背景模块
        # self.label = QtWidgets.QLabel()
        # self.label.setEnabled(True)
        # sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        # sizePolicy.setHorizontalStretch(0)
        # sizePolicy.setVerticalStretch(5)
        # sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        # self.label.setSizePolicy(sizePolicy)
        # self.label.setObjectName("label")
        # pix = QPixmap('D:\Project\IMS\软件界面\查找11.jpg')
        # self.label.setPixmap(pix)
        # # self.label.setStyleSheet("border: 2px solid red")
        # self.label.setScaledContents(True)
        # self.gridLayout.addWidget(self.label, 1, 1, 2, 4)
        #
        # self.page_3.setLayout(self.gridLayout)
#####################################################################################################

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Student information management system"))

    def display(self,index):
        self.stackedWidget.setCurrentIndex(index)

    # def upd(self):
    #     if self.model.rowCount() != 0:
    #         for i in range(self.model.rowCount()):
    #             self.model.removeRow(0)
    #     view().type(self.comboBox.currentIndex(), self.lineEdit, self.file,self.model)
    #
    # def sel(self):
    #     print("sel",self.comboBox.currentIndex())
    #     print("sel-text", self.comboBox.currentText())
    #     print("line",self.lineEdit.text())
    #     if self.comboBox.currentIndex() == 0:
    #         self.lineEdit.setEnabled(False)
    #     else:
    #         self.lineEdit.setEnabled(True)
    #



if __name__ == "__main__":
    App = QApplication(sys.argv)
    MainWindow = Ui_Form("D:\Project\IMS\\UserInfo\dzx.json")
    MainWindow.show()
    sys.exit(App.exec_())



